[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
mypy_path = "src/"
plugins = "strawberry.ext.mypy_plugin, sqlalchemy.ext.mypy.plugin"
python_version = "3.10"
